//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleDigital.DbFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainInfor
    {
        public int Id { get; set; }
        public int DomainId { get; set; }
        public int TabNameId { get; set; }
        public string Content { get; set; }
    
        public virtual TabName TabName { get; set; }
        public virtual Domain Domain { get; set; }
    }
}
