// <auto-generated />
namespace EagleDigital.CodeFirst.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBirthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBirthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201509281745001_AddBirthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
